### ISSUE TITLE
Have an enumsynopsis?

### ISSUE THREAD

**Issue by dourouc05** [docbook/docbook#108]
In the same context as #107 and #60, I would need to represent enumerations (again, C++ ones, but they are highly similar in Java, for instance). I mostly define three concepts: the enumeration (with a synopsis `<enumsynopsis>` and the inline tag `<enumname>`), a named entry in this enumeration (inline tag `<enumidentifier>`), and the corresponding value (the corresponding integer, in C++; inline tag `<enumvalue>`). 

For instance, for this code (C++ and Java equivalents): 

```cpp
enum Colour { red, green, blue };
```

```java
public enum Colour { red, green, blue }
```

the inline elements would be used as follows: `<enumname>Colour</enumname>`, `<enumidentifier>red</enumidentifier>`, `<enumvalue>0</enumvalue>` (in C++, to distinguish from other uses of 0). The synopsis of these enums would be (according to my model): 

```xml
<db:enumsynopsis>
  <db:enumname>Colour</db:enumname>
  <db:enumitem>
    <db:enumidentifier>red</db:enumidentifier>
    <db:enumvalue>0</db:enumvalue>
  </db:enumitem>
  <db:enumitem>
    <db:enumidentifier>green</db:enumidentifier>
    <db:enumvalue>1</db:enumvalue>
  </db:enumitem>
  <db:enumitem>
    <db:enumidentifier>blue</db:enumidentifier>
    <db:enumvalue>2</db:enumvalue>
  </db:enumitem>
</db:enumsynopsis>
```

Here is the corresponding RelaxNG description: 

```
## First the inline elements. 
db.programming.inlines |= db.enumname | db.enumvalue | db.enumidentifier

db.enumname.role.attribute = attribute role { text }
db.enumname.attlist =
   db.enumname.role.attribute?
   & db.common.attributes
   & db.common.linking.attributes
db.enumname = element enumname { db.enumname.attlist, db._text }

db.enumvalue.role.attribute = attribute role { text }
db.enumvalue.attlist =
   db.enumvalue.role.attribute?
   & db.common.attributes
   & db.common.linking.attributes
db.enumvalue = element enumvalue { db.enumvalue.attlist, db._text }

db.enumidentifier.role.attribute = attribute role { text }
db.enumidentifier.attlist =
   db.enumidentifier.role.attribute?
   & db.common.attributes
   & db.common.linking.attributes
db.enumidentifier = element enumidentifier { db.enumidentifier.attlist, db._text }

## Then the synopsis.
db.synopsis.blocks |= db.enumsynopsis

db.enumitem.role.attribute = attribute role { text }
db.enumitem.attlist =
   db.enumitem.role.attribute?
   & db.common.attributes
   & db.common.linking.attributes
db.enumitem = element enumitem { db.enumvalue.attlist, db.enumidentifier, db.enumvalue? }

db.enumsynopsisinfo =
  element enumsynopsisinfo {
    db.funcsynopsisinfo.attlist, db.verbatim.contentmodel
  }

db.enumsynopsis.attlist = 
   db.common.attributes
   & db.common.linking.attributes
   & db.language.attribute?
db.enumsynopsis = 
  element enumsynopsis {
    db.enumsynopsis.attlist, 
    db.programming.inlines+, 
    db.enumsynopsisinfo*,
    db.enumitem*
  }
```

The current deficiency of this description is that is does not allow to represent all possibilities in Java, as it allows methods within enumerations (but this is out of my own scope). Maybe propose to have a `<classsynopsis>`, which contains the methods and an `<enumsynopsis>`?

**Comment by dourouc05** [comment]
Replying to https://lists.oasis-open.org/archives/docbook-tc/201810/msg00010.html. 

- This is not really aimed at a specific language, as enums are quite common (C, C++, Julia, Java, Fortran, C#, HHVM at least -- see https://en.wikipedia.org/wiki/Enumerated_type, for instance). The proposed content model would fit many languages I know of (the exception being that Java enums are full classes, i.e. one can add methods to an enum, but that could be worked around using a `classsynopsis` around the proposed `enumsynopsis`). 
- The content model is quite different from other elements allowed in classes, I don't think a new `role` would help. 
- This would help structure a documentation (and index it), with for instance autogeneration of a table containing all values of an enumeration (like http://doc.qt.io/qt-5/qwidget.html#RenderFlag-enum, but without the Description column). Without this kind of tag, the information of an enumerated type would be completely lost, which is inconsistent with having the `classsynopsis` tags and the like.

**Comment by kosek** [comment]
Adding this element (and other *synopsis) elements you propose would be huge effort.

But you haven't described your use case for this. I can hardly imagine that someone would be typing these by hand. Common scenario is to use some tool to extract all this information from source code and then integrate it into existing document. For such scenario you don't have to preserve "parsed source code" but it's usually enough to generate some presentational markup. For example table listing all possible values for enum. I don't think that we should be inventing something similar to for example intermediate Doxygen format and putting it into DocBook. Or do you have different use case in mind?

**Comment by dourouc05** [comment]
My use case is to describe the Qt documentation in DocBook, the files being generated automatically from the source code (through qdoc and custom XSLT sheets). The goal is to translate the documentation (by hand, mostly) and, next, to provide other services around the information stored in the documentation (this is why I would like to extract as much information from it as possible, to avoid reprocessing tens of thousands of classes multiple times). This documentation is structured in a way that I cannot see a useful way of storing all the documentation within `enumsynopsis`, it would only be a useful tag to store parsed information. (This also lead to the choice of DocBook, as it is a standard that keeps compatibility across minor version, unlike Doxygen --- and the documentation would need to be updated with each version, so that the previous files remain useful for several years.)

After having a look at Doxygen (https://github.com/doxygen/doxygen/blob/master/templates/xml/compound.xsd#L202, more specifically), this would store more than I need, but I could work with that (the only problem being that it is not really consistent with the rest of DocBook: the name of the enumeration is stored in an attribute, not in a tag, mostly).

**Comment by bobstayton** [comment]
The DocBook Technical Committee is reluctant to add a large number of new elements to a schema that is already very large.  The changes you are suggesting seem to be very specific to your project, and it isn't clear that they would be used very much by others.  Since the DocBook RNG schema is relatively easy to customize, why not just add these elements as a customization for your project?  

Another way of extending markup without customizing the schema is to use the role attribute on existing elements. The role attribute was specifically inserted to allow extension of the semantics of any element for local purposes.  Without further analysis I don't know if this would work with the elements that you want to change, though.

If you can convince us that these new elements would be used beyond your project, another option is to create a standard extension to the DocBook Schema, similar to the Publisher's extensions.  That way only those people who need these new elements could use them without burdening those who don't need this level of detailed markup.

**Comment by bobstayton** [comment]
The DocBook Technical Committee recognized the need and would like to develop this as a schema extension similar to the DocBook Publishers schema. After development, testing, and final approval at OASIS, it would be published as part of the standard schema set.  The DocBook XSL stylesheets (which are not part of the standard) would also be updated to handle the new elements.

The one caveat was that the extension not be tied to a particular programming language.  That means any new features would need to be applicable in describing at least two languages, hopefully more. 

Due to the limited time TC members have available, this extension will proceed faster if the TC receives a fully developed proposal rather than developing it ourselves.  Would you be willing to pull together all of your suggestions into a single proposal, make any changes to ensure it is general and not specific to a particular language, and submit it as a new issue?  

After we have an extension candidate, we will publicize it on the docbook mailing lists to get feedback from other DocBook users who document programming languages.

**Comment by dourouc05** [comment]
Nice, thank you for the follow-up! No problem for having it more general than one programming language (that is already something I had in mind). 

What level of writing do you need for this proposal? I guess it is something like http://docs.oasis-open.org/docbook/specs/publishers-1.0-spec-cs-01.html?

**Comment by shudson310** [comment]
Superceded by #111
